### ISSUE TITLE
Hardcoded indexes?

### ISSUE THREAD

**Issue by tuananhta1993** [nttuan8/DL_Tutorial#1]
https://github.com/nttuan8/DL_Tutorial/blob/5ad08e04ac17fec5ea7b1af6aa7f42e47d63e49b/L2/l2.py#L23

Mình nghĩ đoạn này bạn nên thay bằng

```python
x_chovay = x[y[:,0]==1.]
x_tuchoi = x[y[:,0]==0.]

plt.scatter(x_chovay[:, 0], x_chovay[:, 1], c='red', edgecolors='none', s=30, label='cho vay')
plt.scatter(x_tuchoi[:, 0],x_tuchoi[:, 1], c='blue', edgecolors='none', s=30, label='từ chối')
```

Như thế mình sẽ ko cần phải rely vào dataset.

**Comment by nttuan8** [comment]
Thanks bạn, lúc đấy mình hơi vội nên hardcode, mình đã sửa.
